In [21]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
np.set_printoptions(suppress=True)
from sklearn.preprocessing import MinMaxScaler
from pylab import *
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False 
from sklearn import metrics
from sklearn.metrics import mean_squared_error #均方误差
from sklearn.metrics import mean_absolute_error #平方绝对误差


In [7]:
data=pd.read_excel('newdata.xlsx')
data.head()

Unnamed: 0       Date  Contest number   Word  Number of  reported results  \
0           0 2022-12-31             560  manly                        20380   
1           1 2022-12-30             559  molar                        21204   
2           2 2022-12-29             558  havoc                        20001   
3           3 2022-12-28             557  impel                        20160   
4           4 2022-12-27             556  condo                        20879   

   Number in hard mode  1 try  2 tries  3 tries  4 tries  ...  r  s  t  u  v  \
0                 1899      0        2       17       37  ...  0  0  0  0  0   
1                 1973      0        4       21       38  ...  1  0  0  0  0   
2                 1919      0        2       16       38  ...  0  0  0  0  1   
3                 1937      0        3       21       40  ...  0  0  0  0  0   
4                 2012      0        2       17       35  ...  0  0  0  0  0   

   w  x  y  z  hard pecent  
0  0  0  1  0     0.093180  
1  0  0  0  0     0.093048  
2  0  0  0  0     0.095945  
3  0  0  0  0     0.096081  
4  0  0  0  0     0.096365  

[5 rows x 41 columns]

In [8]:
data.columns

Index(['Unnamed: 0', 'Date', 'Contest number', 'Word',
       'Number of  reported results', 'Number in hard mode', '1 try',
       '2 tries', '3 tries', '4 tries', '5 tries', '6 tries',
       '7 or more tries (X)', 'len', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h',
       'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
       'w', 'x', 'y', 'z', 'hard pecent'],
      dtype='object')

In [9]:
from collections import Counter
aa='a、b、c、d、e、f、g、h、i、j、k、l、m、n、o、p、q、r、s、t、u、v、w、x、y、z'.split('、')
i='eerie'
tt=Counter(i.strip())
bb=[0]*26
for j in tt:
    bb[aa.index(j)]=tt[j]
bb

[0, 0, 0, 0, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]

In [27]:
cc=bb

In [22]:
import pandas as pd
from numpy import *
import numpy as np
from sklearn.neural_network import MLPRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression

import xgboost as xgb
import lightgbm as lgb
import numpy as np


import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error,r2_score
from sklearn.multioutput import MultiOutputRegressor,RegressorChain 
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split
def mape(actual, pred): 
    actual, pred = np.array(actual), np.array(pred)
    return np.mean(np.abs((actual - pred) / actual))


In [25]:
X=data[['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h',
       'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
       'w', 'x', 'y', 'z']]
Y=data[[ '1 try',
       '2 tries', '3 tries', '4 tries', '5 tries', '6 tries',
       '7 or more tries (X)']]

tr_x,te_x,tr_y,te_y=train_test_split(X ,Y,test_size=0.1,random_state=5)

In [28]:
model=RegressorChain(MLPRegressor(hidden_layer_sizes=10,max_iter=1000))
model.fit(tr_x,tr_y)
print("神经网络:")
for i in range(7):
    print(Y.columns[i])
    trX_Y=model.predict(tr_x)[:,i].reshape(-1,1)
    tre_Y=model.predict(te_x)[:,i].reshape(-1,1)
    print("训练集平均绝对百分比误差:{:.3f}".format(mape(trX_Y,tr_y.values[:,i].reshape(-1,1))))
    print("测试集平均绝对百分比误差:{:.3f}".format(mape(tre_Y,te_y.values[:,i].reshape(-1,1))))
    print()
model.predict(np.array(cc).reshape(1, -1))

神经网络:
1 try
训练集平均绝对百分比误差:1.370
测试集平均绝对百分比误差:1.421

2 tries
训练集平均绝对百分比误差:0.724
测试集平均绝对百分比误差:0.424

3 tries
训练集平均绝对百分比误差:0.220
测试集平均绝对百分比误差:0.194

4 tries
训练集平均绝对百分比误差:0.114
测试集平均绝对百分比误差:0.124

5 tries
训练集平均绝对百分比误差:0.148
测试集平均绝对百分比误差:0.194

6 tries
训练集平均绝对百分比误差:0.398
测试集平均绝对百分比误差:0.484

7 or more tries (X)
训练集平均绝对百分比误差:0.998
测试集平均绝对百分比误差:1.079



array([[ 0.58137445,  8.08008622, 24.72970571, 31.8133658 , 22.54581941,
        10.16208832,  1.70634877]])

In [29]:
model=RegressorChain(LinearRegression())
model.fit(tr_x,tr_y)
print("\n线性回归:")

for i in range(7):
    print(Y.columns[i])
    trX_Y=model.predict(tr_x)[:,i].reshape(-1,1)
    tre_Y=model.predict(te_x)[:,i].reshape(-1,1)
    print("训练集平均绝对百分比误差:{:.3f}".format(mape(trX_Y,tr_y.values[:,i].reshape(-1,1))))
    print("测试集平均绝对百分比误差:{:.3f}".format(mape(tre_Y,te_y.values[:,i].reshape(-1,1))))
    print()
model.predict(np.array(cc).reshape(1, -1))


线性回归:
1 try
训练集平均绝对百分比误差:1.678
测试集平均绝对百分比误差:1.088

2 tries
训练集平均绝对百分比误差:0.958
测试集平均绝对百分比误差:0.394

3 tries
训练集平均绝对百分比误差:0.217
测试集平均绝对百分比误差:0.224

4 tries
训练集平均绝对百分比误差:0.115
测试集平均绝对百分比误差:0.122

5 tries
训练集平均绝对百分比误差:0.158
测试集平均绝对百分比误差:0.177

6 tries
训练集平均绝对百分比误差:0.367
测试集平均绝对百分比误差:0.392

7 or more tries (X)
训练集平均绝对百分比误差:0.777
测试集平均绝对百分比误差:0.757



array([[ 0.80691408,  8.97951027, 24.46280171, 29.85321086, 21.54640271,
        10.16407526,  3.15636345]])

In [30]:
model=RegressorChain(DecisionTreeRegressor(max_depth=50,random_state=0))
model.fit(tr_x,tr_y)
print("\n决策树回归:")

for i in range(7):
    print(Y.columns[i])
    trX_Y=model.predict(tr_x)[:,i].reshape(-1,1)
    tre_Y=model.predict(te_x)[:,i].reshape(-1,1)
    print("训练集平均绝对百分比误差:{:.3f}".format(mape(trX_Y,tr_y.values[:,i].reshape(-1,1))))
    print("测试集平均绝对百分比误差:{:.3f}".format(mape(tre_Y,te_y.values[:,i].reshape(-1,1))))
    print()
model.predict(np.array(cc).reshape(1, -1))


决策树回归:
1 try
训练集平均绝对百分比误差:nan
测试集平均绝对百分比误差:nan

2 tries
训练集平均绝对百分比误差:nan
测试集平均绝对百分比误差:0.678

3 tries
训练集平均绝对百分比误差:0.003
测试集平均绝对百分比误差:0.384

4 tries
训练集平均绝对百分比误差:0.002
测试集平均绝对百分比误差:0.151

5 tries
训练集平均绝对百分比误差:0.003
测试集平均绝对百分比误差:0.363

6 tries
训练集平均绝对百分比误差:0.005
测试集平均绝对百分比误差:0.859

7 or more tries (X)
训练集平均绝对百分比误差:nan
测试集平均绝对百分比误差:inf



array([[ 1., 10., 26., 32., 21.,  9.,  1.]])

In [31]:
model=RegressorChain(RandomForestRegressor(max_depth=20,n_estimators=1000,random_state=0))
model.fit(tr_x,tr_y)
print("\n随机森林回归:")

for i in range(7):
    print(Y.columns[i])
    trX_Y=model.predict(tr_x)[:,i].reshape(-1,1)
    tre_Y=model.predict(te_x)[:,i].reshape(-1,1)
    print("训练集平均绝对百分比误差:{:.3f}".format(mape(trX_Y,tr_y.values[:,i].reshape(-1,1))))
    print("测试集平均绝对百分比误差:{:.3f}".format(mape(tre_Y,te_y.values[:,i].reshape(-1,1))))
    print()
model.predict(np.array(cc).reshape(1, -1))


随机森林回归:
1 try
训练集平均绝对百分比误差:0.722
测试集平均绝对百分比误差:1.448

2 tries
训练集平均绝对百分比误差:0.169
测试集平均绝对百分比误差:0.548

3 tries
训练集平均绝对百分比误差:0.120
测试集平均绝对百分比误差:0.267

4 tries
训练集平均绝对百分比误差:0.075
测试集平均绝对百分比误差:0.118

5 tries
训练集平均绝对百分比误差:0.091
测试集平均绝对百分比误差:0.233

6 tries
训练集平均绝对百分比误差:0.255
测试集平均绝对百分比误差:0.509

7 or more tries (X)
训练集平均绝对百分比误差:0.680
测试集平均绝对百分比误差:1.076



array([[ 0.23015385,  3.51320833, 18.326     , 31.263     , 27.5       ,
        15.751     ,  2.861     ]])

In [32]:
model=RegressorChain(lgb.LGBMRegressor())
model.fit(tr_x,tr_y)
print("\nLGBM回归:")

for i in range(7):
    print(Y.columns[i])
    trX_Y=model.predict(tr_x)[:,i].reshape(-1,1)
    tre_Y=model.predict(te_x)[:,i].reshape(-1,1)
    print("训练集平均绝对百分比误差:{:.3f}".format(mape(trX_Y,tr_y.values[:,i].reshape(-1,1))))
    print("测试集平均绝对百分比误差:{:.3f}".format(mape(tre_Y,te_y.values[:,i].reshape(-1,1))))
    print()
model.predict(np.array(cc).reshape(1, -1))


LGBM回归:
1 try
训练集平均绝对百分比误差:0.996
测试集平均绝对百分比误差:1.783

2 tries
训练集平均绝对百分比误差:0.386
测试集平均绝对百分比误差:0.463

3 tries
训练集平均绝对百分比误差:0.201
测试集平均绝对百分比误差:0.255

4 tries
训练集平均绝对百分比误差:0.115
测试集平均绝对百分比误差:0.126

5 tries
训练集平均绝对百分比误差:0.182
测试集平均绝对百分比误差:0.229

6 tries
训练集平均绝对百分比误差:0.417
测试集平均绝对百分比误差:0.554

7 or more tries (X)
训练集平均绝对百分比误差:1.365
测试集平均绝对百分比误差:1.905



array([[ 0.49282038,  7.10428038, 23.887638  , 30.54342356, 23.63403641,
        11.79332021,  1.9465991 ]])

In [33]:
model=RegressorChain(xgb.XGBRegressor())
model.fit(tr_x,tr_y)
print("\nXGBRegressor:")

for i in range(7):
    print(Y.columns[i])
    trX_Y=model.predict(tr_x)[:,i].reshape(-1,1)
    tre_Y=model.predict(te_x)[:,i].reshape(-1,1)
    print("训练集平均绝对百分比误差:{:.3f}".format(mape(trX_Y,tr_y.values[:,i].reshape(-1,1))))
    print("测试集平均绝对百分比误差:{:.3f}".format(mape(tre_Y,te_y.values[:,i].reshape(-1,1))))
    print()
model.predict(np.array(cc).reshape(1, -1))


XGBRegressor:
1 try
训练集平均绝对百分比误差:0.653
测试集平均绝对百分比误差:29.106

2 tries
训练集平均绝对百分比误差:0.053
测试集平均绝对百分比误差:0.451

3 tries
训练集平均绝对百分比误差:0.013
测试集平均绝对百分比误差:0.264

4 tries
训练集平均绝对百分比误差:0.008
测试集平均绝对百分比误差:0.131

5 tries
训练集平均绝对百分比误差:0.008
测试集平均绝对百分比误差:0.213

6 tries
训练集平均绝对百分比误差:0.021
测试集平均绝对百分比误差:0.644

7 or more tries (X)
训练集平均绝对百分比误差:0.125
测试集平均绝对百分比误差:2.315



array([[ 0.11630215,  3.62400508, 19.63280106, 34.7289238 , 26.79278374,
        12.05149937,  1.71731436]])